{{- $keycloakName := .Values.keycloak.name -}}
{{- if .Values.keycloak.realms }}
{{- range $realm := .Values.keycloak.realms }}
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: {{ $realm.name }} 
  labels:
    realm: {{ $realm.name }} 
spec:
  instanceSelector:
    matchLabels:
      app: {{ $keycloakName }}
  realm:
    displayName: {{ $realm.displayName }}
    enabled: {{ $realm.enabled }}
    realm: {{ $realm.name }} 
{{- end }}
{{- end }}